In [86]:
import numpy as np

def calculate(list):
    
    if len(list) < 9:
        return "List must contain nine numbers."
        
   
    array=np.array(list).reshape(3,3)
    
    calculations = dict()
    
    calculations['mean']= [np.mean(array,axis=0).tolist(), np.mean(array,axis=1).tolist(), np.mean(array)]
    calculations['variance']= [np.var(array,axis=0).tolist(), np.var(array,axis=1).tolist(), np.var(array)]
    calculations['standard deviation']= [np.std(array,axis=0).tolist(), np.std(array,axis=1).tolist(), np.std(array)]
    calculations['max']= [np.max(array,axis=0).tolist(), np.max(array,axis=1).tolist(), np.max(array)]
    calculations['min']= [np.min(array,axis=0).tolist(), np.min(array,axis=1).tolist(), np.min(array)]
    calculations['sum']= [np.sum(array,axis=0).tolist(), np.sum(array,axis=1).tolist(), np.sum(array)]
    

    return calculations

In [88]:
calculate([0,1,2,3,4,5,6,7,8])

'List must contain nine numbers.'

In [41]:
array=np.array([0,1,2,3,4,5,6,7,8]).reshape(3,3)
print(array)
print(array[0,:])

mean=np.mean(array,axis=0)
lista=list(mean)

print(mean)
print(lista)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[0 1 2]
[3. 4. 5.]
[3.0, 4.0, 5.0]
